name: 🔧 Fix
description: "코드 수정"
title: '[🔧 Fix] '
labels: ['🔧 Fix']
body:
  - type: textarea
    id: fix-description
    attributes:
      label: 📍 수정할 내용
      placeholder: |
        - 수정이 필요한 코드나 기능을 설명해주세요
    validations:
      required: true
  - type: textarea
    id: fix-checklist
    attributes:
      label: ✅ To-Do
      description: |
        아래 체크리스트를 작성해주세요
      placeholder: |
        - [ ] 수정 사항 확인
        - [ ] 테스트 진행
        - [ ] 코드 리뷰
    validations:
      required: true
  - type: textarea
    id: fix-more
    attributes:
      label: 🎻 기타
      description: 더 하고 싶은 말이 있다면 작성해 주세요
    validations:
      required: false