name: 🚑 Hotfix
description: "긴급 버그 수정"
title: '[🚑 Hotfix] '
labels: ['🚑 Hotfix']
body:
  - type: textarea
    id: hotfix-description
    attributes:
      label: 📍 긴급 수정 사항
      placeholder: |
        - 현재 발생한 문제점
        - 영향을 받는 기능
    validations:
      required: true
  - type: textarea
    id: hotfix-checklist
    attributes:
      label: ✅ To-Do
      description: |
        아래 체크리스트를 작성해주세요
      placeholder: |
        - [ ] 원인 파악
        - [ ] 핫픽스 적용
        - [ ] main 브랜치 반영
        - [ ] develop 브랜치 반영
    validations:
      required: true
  - type: textarea
    id: hotfix-more
    attributes:
      label: 🎻 기타
      description: 더 하고 싶은 말이 있다면 작성해 주세요
    validations:
      required: false